### PR TITLE
Add support for Gists and GitLab.com

### PR DESCRIPTION
**Pull request by betatim**
As the title suggests, the extension now understands gists and gitlab.com

It isn't the prettiest JS but I tried to reduce repetition.

### CODE REVIEW

**Comment by Carreau** [comment]
Can you try to login to and access https://addons.mozilla.org/en-US/developers/addon/open-with-binder ?

**Comment by Carreau** [comment]
And you should be admin now, so you can self-merge, and hopefully publish :-)

**Review by Carreau — APPROVED** [review]

**Comment by betatim** [comment]
This amount of power mwahahaha ...

tenor 1

**Comment by Carreau** [comment]
Want to tag the merge commit and push the tag ? 

Did you just `make release`  to make a release and upload the corresponding zip to ff ?

**Comment by betatim** [comment]
Jupp, I used `make` to make the release. Also ran `web-ext build` afterwards for curiosity. Seem to produce the same zip files.

I think the tag was only created locally because I have this repo as remote "upstream" not "origin" so when `git push` was executed it didn't end up here. Created the tag by hand instead.

**Pull request merged**
