### PR TITLE
release 0.3.1 and add  assets

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by Carreau** [comment]
@choldgraf, @betatim  I'm going to suggest we move that to the JupyterHub org. In particular that will prevent me from being the bottle neck and pushing here by mistake.

**Comment by Carreau** [comment]
Actually we need a 3.2 as now chrome require 128px wide icons.

**Comment by choldgraf** [comment]
I'm all for it!

**Comment by betatim** [comment]
Moving sounds good to me. I tagged the revision I used to make v0.3.0 just now. Hadn't seen this PR until after.

One thing I am not clear on: this talks about 3.1 but I would have said the next release is 0.3.1? I don't care much either way just that we pick one way :)

**Pull request merged**
